/**
 * Database Seed Script
 * Populates the database with 100 sample BBQ recipes
 */

require('dotenv').config();
const db = require('../config/database');

// Recipe data organized by category
const recipes = {
    pork: [
        { title: 'Classic Smoked Pulled Pork', description: 'Tender, smoky pulled pork with a beautiful bark. Perfect for sandwiches.', prep_time: 30, cook_time: 480, servings: 12, featured: 1, ingredients: ['8 lb pork shoulder (bone-in)', '1/4 cup yellow mustard', '1/2 cup brown sugar', '1/4 cup paprika', '2 tbsp garlic powder', '2 tbsp onion powder', '1 tbsp black pepper', '1 tbsp salt', '1 tsp cayenne pepper', 'Apple wood chips'], instructions: ['Trim excess fat from pork shoulder, leaving 1/4 inch cap.', 'Coat pork with yellow mustard as a binder.', 'Mix all dry ingredients to create the rub.', 'Apply rub generously, covering all surfaces.', 'Let rest in refrigerator overnight.', 'Preheat smoker to 225°F with apple wood.', 'Place pork fat-side up on smoker.', 'Smoke until internal temp reaches 165°F (about 6 hours).', 'Wrap in butcher paper and continue cooking.', 'Remove at 203°F internal temperature.', 'Rest for 1 hour before pulling.', 'Pull pork and mix with any collected juices.'] },
        { title: 'Competition-Style Baby Back Ribs', description: 'Fall-off-the-bone tender ribs with the perfect balance of smoke, sweetness, and spice.', prep_time: 20, cook_time: 300, servings: 4, featured: 1, ingredients: ['2 racks baby back ribs', '1/4 cup brown sugar', '2 tbsp paprika', '1 tbsp chili powder', '1 tbsp garlic powder', '1 tbsp onion powder', '1 tsp cumin', '1 tsp black pepper', '1/2 cup apple juice', '1 cup BBQ sauce', 'Cherry wood chips'], instructions: ['Remove membrane from back of ribs.', 'Mix dry ingredients to create rub.', 'Apply rub generously on both sides.', 'Let ribs rest for 30 minutes.', 'Preheat smoker to 250°F.', 'Smoke ribs meat-side up for approximately 3 hours.', 'Wrap ribs in foil with apple juice.', 'Cook for approximately 1.5 hours more.', 'Unwrap and brush with BBQ sauce.', 'Ribs are done when internal temp reaches 195-203°F and meat pulls back from bones.', 'Rest 10 minutes before cutting.'] },
        { title: 'Smoked Pork Belly Burnt Ends', description: 'Sweet, sticky, and incredibly tender pork belly cubes with caramelized edges.', prep_time: 20, cook_time: 240, servings: 8, ingredients: ['5 lb pork belly', '1/4 cup BBQ rub', '1 cup BBQ sauce', '1/2 cup honey', '4 tbsp butter', '1/4 cup brown sugar'], instructions: ['Cut pork belly into 1.5-inch cubes.', 'Season generously with BBQ rub.', 'Smoke at 250°F for approximately 2.5 hours.', 'Transfer to aluminum pan.', 'Add butter, honey, and brown sugar.', 'Cover and cook approximately 1 hour more.', 'Uncover and add BBQ sauce.', 'Cook until internal temp reaches 200°F and cubes are probe tender, about 30 more minutes.'] },
        { title: 'Honey Garlic Smoked Pork Chops', description: 'Juicy bone-in pork chops with a sweet honey garlic glaze.', prep_time: 15, cook_time: 90, servings: 4, ingredients: ['4 bone-in pork chops (1.5 inch thick)', '1/4 cup honey', '4 cloves garlic, minced', '2 tbsp soy sauce', '1 tbsp olive oil', '1 tsp smoked paprika', 'Salt and pepper'], instructions: ['Brine pork chops for 2 hours.', 'Mix honey, garlic, soy sauce, and oil for glaze.', 'Season chops with paprika, salt, and pepper.', 'Smoke at 250°F for 45 minutes.', 'Brush with glaze every 15 minutes.', 'Remove at 145°F internal temp.', 'Rest 5 minutes before serving.'] },
        { title: 'Smoked Pork Tenderloin', description: 'Lean and flavorful smoked pork tenderloin with herb crust.', prep_time: 15, cook_time: 75, servings: 4, ingredients: ['2 pork tenderloins (about 1 lb each)', '2 tbsp olive oil', '2 tbsp fresh rosemary, chopped', '1 tbsp fresh thyme', '4 cloves garlic, minced', 'Salt and pepper'], instructions: ['Trim silver skin from tenderloins.', 'Mix oil with herbs and garlic.', 'Coat tenderloins with herb mixture.', 'Season with salt and pepper.', 'Smoke at 275°F for 1 hour.', 'Remove at 145°F internal temp.', 'Rest 10 minutes, slice and serve.'] },
        { title: 'Carolina Vinegar Pulled Pork', description: 'Eastern Carolina-style pulled pork with tangy vinegar sauce.', prep_time: 25, cook_time: 540, servings: 14, ingredients: ['10 lb pork shoulder', '2 cups apple cider vinegar', '1/4 cup brown sugar', '2 tbsp red pepper flakes', '1 tbsp black pepper', '1 tbsp salt', '1 tsp cayenne'], instructions: ['Season pork with salt and pepper.', 'Smoke at 225°F for 8-9 hours.', 'Mix vinegar sauce ingredients.', 'Pull pork when it reaches 203°F.', 'Toss with vinegar sauce.', 'Serve on buns with coleslaw.'] },
        { title: 'Smoked Pork Shoulder Steaks', description: 'Quick-cooking pork shoulder steaks with bold seasonings.', prep_time: 10, cook_time: 120, servings: 4, ingredients: ['4 pork shoulder steaks', '2 tbsp BBQ rub', '1/4 cup apple juice', 'Hickory wood chips'], instructions: ['Season steaks with BBQ rub.', 'Smoke at 275°F for 1.5 hours.', 'Spritz with apple juice hourly.', 'Remove at 180°F internal temp.', 'Rest 5 minutes before serving.'] },
        { title: 'Maple Bourbon Glazed Ham', description: 'Holiday-worthy smoked ham with maple bourbon glaze.', prep_time: 20, cook_time: 180, servings: 16, ingredients: ['10 lb bone-in ham', '1 cup maple syrup', '1/2 cup bourbon', '1/4 cup Dijon mustard', '1/4 cup brown sugar', 'Whole cloves'], instructions: ['Score ham in diamond pattern.', 'Insert cloves at intersections.', 'Mix glaze ingredients.', 'Smoke ham at 275°F.', 'Glaze every 30 minutes.', 'Cook until 140°F internal.', 'Rest 20 minutes before carving.'] },
        { title: 'Smoked Pork Spare Ribs', description: 'St. Louis-style spare ribs with rich, smoky flavor.', prep_time: 25, cook_time: 360, servings: 6, ingredients: ['2 racks spare ribs', '1/4 cup yellow mustard', '1/2 cup BBQ rub', 'Apple cider vinegar spray', 'BBQ sauce'], instructions: ['Trim ribs St. Louis style.', 'Apply mustard as binder.', 'Season with BBQ rub.', 'Smoke at 250°F for approximately 3 hours.', 'Spritz hourly with vinegar.', 'Wrap and cook approximately 2 more hours.', 'Sauce and finish until internal temp reaches 195-203°F between the bones.', 'Rest 10 minutes before cutting.'] },
        { title: 'Smoked Sausage Links', description: 'Homemade smoked pork sausages with perfect snap.', prep_time: 45, cook_time: 120, servings: 8, ingredients: ['5 lb ground pork', '2 tbsp salt', '1 tbsp black pepper', '1 tbsp paprika', '1 tsp sage', '1/2 tsp red pepper flakes', 'Hog casings'], instructions: ['Mix pork with seasonings.', 'Stuff into casings.', 'Twist into 6-inch links.', 'Dry in fridge overnight.', 'Smoke at 225°F for 2 hours.', 'Internal temp should reach 160°F.'] },
        { title: 'Cuban Mojo Pork', description: 'Citrus-marinated smoked pork with Cuban flavors.', prep_time: 30, cook_time: 300, servings: 8, ingredients: ['5 lb pork shoulder', '1 cup orange juice', '1/2 cup lime juice', '10 garlic cloves', '2 tbsp cumin', '2 tbsp oregano', '1/4 cup olive oil'], instructions: ['Blend marinade ingredients.', 'Marinate pork overnight.', 'Smoke at 275°F for approximately 5 hours.', 'Baste with marinade hourly.', 'Pull when internal temp reaches 203°F and is probe tender.', 'Serve with rice and beans.'] },
        { title: 'Smoked Pork Loin Roast', description: 'Elegant smoked pork loin with apple glaze.', prep_time: 15, cook_time: 150, servings: 8, ingredients: ['4 lb boneless pork loin', '1 cup apple jelly', '2 tbsp Dijon mustard', '1 tbsp rosemary', 'Salt and pepper'], instructions: ['Season pork loin all over.', 'Smoke at 250°F for 2 hours.', 'Mix apple jelly glaze.', 'Brush glaze on pork.', 'Continue cooking to 145°F.', 'Rest 15 minutes before slicing.'] },
        { title: 'Asian BBQ Pork Belly', description: 'Chinese-inspired smoked pork belly with hoisin glaze.', prep_time: 20, cook_time: 240, servings: 6, ingredients: ['3 lb pork belly', '1/2 cup hoisin sauce', '1/4 cup soy sauce', '2 tbsp honey', '1 tbsp five spice powder', '4 cloves garlic'], instructions: ['Score pork belly skin.', 'Mix glaze ingredients.', 'Marinate pork 4 hours.', 'Smoke at 275°F for approximately 3 hours.', 'Glaze every 30 minutes.', 'Cook until internal temp reaches 200°F and is probe tender.', 'Crisp skin under broiler.', 'Slice and serve.'] },
        { title: 'Memphis Dry Rub Ribs', description: 'Classic Memphis-style ribs without sauce.', prep_time: 15, cook_time: 300, servings: 4, featured: 1, ingredients: ['2 racks baby back ribs', '1/4 cup paprika', '2 tbsp brown sugar', '1 tbsp chili powder', '1 tbsp garlic powder', '1 tbsp onion powder', '1 tsp cayenne', '1 tsp black pepper'], instructions: ['Remove membrane from ribs.', 'Mix all rub ingredients.', 'Apply rub generously.', 'Refrigerate 2 hours.', 'Smoke at 250°F for approximately 5 hours.', 'Ribs are done when internal temp reaches 195-203°F between the bones.', 'No sauce - serve dry!'] },
        { title: 'Smoked Porchetta', description: 'Italian-style rolled pork with fennel and herbs.', prep_time: 45, cook_time: 240, servings: 10, ingredients: ['6 lb pork belly with skin', '3 tbsp fennel seeds', '4 tbsp fresh rosemary', '6 cloves garlic', '2 tbsp olive oil', 'Salt and pepper'], instructions: ['Toast and grind fennel seeds.', 'Mix with herbs and garlic.', 'Spread on pork belly.', 'Roll tightly and tie.', 'Score skin, season with salt.', 'Smoke at 275°F for approximately 4 hours.', 'Cook until internal temp reaches 165°F.', 'Crisp skin at high heat.', 'Rest 20 minutes before slicing.'] },
        { title: 'Smoked Pork Cheeks', description: 'Meltingly tender pork cheeks braised in BBQ sauce.', prep_time: 15, cook_time: 240, servings: 4, ingredients: ['2 lb pork cheeks', '1 cup BBQ sauce', '1/2 cup beef broth', '1 onion, sliced', 'BBQ rub'], instructions: ['Season pork cheeks with rub.', 'Smoke at 250°F for approximately 2 hours.', 'Transfer to braising pan.', 'Add sauce, broth, onions.', 'Cover and braise until internal temp reaches 200°F and meat is fork tender.', 'Serve over mashed potatoes.'] },
        { title: 'Cajun Smoked Pork Butt', description: 'Spicy Louisiana-style smoked pork.', prep_time: 20, cook_time: 480, servings: 12, ingredients: ['8 lb pork butt', '3 tbsp Cajun seasoning', '1 tbsp paprika', '1 tbsp garlic powder', '1 tbsp onion powder', '1 tsp cayenne', '1 tsp thyme'], instructions: ['Mix all seasonings.', 'Coat pork generously.', 'Refrigerate overnight.', 'Smoke at 225°F for 8 hours.', 'Wrap at 165°F internal.', 'Pull at 203°F internal.'] },
        { title: 'Smoked Country-Style Ribs', description: 'Meaty country-style ribs with sweet glaze.', prep_time: 10, cook_time: 180, servings: 6, ingredients: ['3 lb country-style ribs', '2 tbsp BBQ rub', '1 cup BBQ sauce', '1/4 cup honey'], instructions: ['Season ribs with rub.', 'Smoke at 275°F for approximately 2.5 hours.', 'Mix sauce with honey.', 'Brush ribs with glaze.', 'Cook until internal temp reaches 195°F and meat is tender.', 'Glaze again before serving.'] },
        { title: 'Smoked Pork Crown Roast', description: 'Impressive crown roast for special occasions.', prep_time: 30, cook_time: 180, servings: 10, ingredients: ['8 lb pork crown roast', '1/4 cup olive oil', '3 tbsp fresh herbs', '4 cloves garlic', 'Salt and pepper', 'Apple stuffing'], instructions: ['Season roast inside and out.', 'Cover bone tips with foil.', 'Smoke at 275°F for 3 hours.', 'Fill center with stuffing.', 'Cook until 145°F internal.', 'Rest 20 minutes before carving.'] },
        { title: 'Smoked Stuffed Pork Loin', description: 'Pork loin stuffed with spinach and cheese.', prep_time: 30, cook_time: 120, servings: 6, ingredients: ['3 lb pork loin', '2 cups fresh spinach', '1 cup mozzarella', '1/2 cup sun-dried tomatoes', '4 cloves garlic', 'Italian seasoning'], instructions: ['Butterfly pork loin.', 'Layer spinach, cheese, tomatoes.', 'Roll and tie with twine.', 'Season exterior.', 'Smoke at 275°F for approximately 2 hours.', 'Cook until internal temp reaches 145°F.', 'Rest 10 minutes, slice to serve.'] }
    ],
    beef: [
        { title: 'Texas-Style Smoked Brisket', description: 'The king of BBQ - tender, juicy brisket with perfect bark and smoke ring.', prep_time: 30, cook_time: 720, servings: 16, featured: 1, ingredients: ['14 lb whole packer brisket', '1/4 cup coarse black pepper', '1/4 cup kosher salt', '2 tbsp garlic powder', 'Post oak wood'], instructions: ['Trim brisket, leaving 1/4 inch fat cap.', 'Mix salt, pepper, and garlic for rub.', 'Apply rub generously all over.', 'Let rest at room temp for 1 hour.', 'Preheat smoker to 250°F with post oak.', 'Place brisket fat-side up.', 'Smoke until bark sets (about 6 hours).', 'Wrap in butcher paper at 165°F.', 'Continue cooking until 203°F probe tender.', 'Rest in cooler for 2 hours minimum.', 'Slice against the grain and serve.'] },
        { title: 'Smoked Beef Short Ribs', description: 'Beefy, rich, and incredibly tender plate-style short ribs.', prep_time: 20, cook_time: 480, servings: 6, featured: 1, ingredients: ['6 lb beef plate short ribs', '2 tbsp black pepper', '2 tbsp kosher salt', '1 tbsp garlic powder', '1 tbsp onion powder', 'Oak wood chunks'], instructions: ['Trim excess fat from ribs.', 'Mix seasonings for rub.', 'Season ribs generously.', 'Smoke at 275°F for approximately 6-8 hours.', 'Spritz with beef broth hourly.', 'Ribs are done when internal temp reaches 203°F and probe tender.', 'Rest 30 minutes before serving.'] },
        { title: 'Smoked Tri-Tip', description: 'California-style smoked tri-tip with Santa Maria seasoning.', prep_time: 15, cook_time: 90, servings: 6, ingredients: ['3 lb tri-tip roast', '2 tbsp garlic powder', '1 tbsp onion powder', '1 tbsp black pepper', '1 tbsp salt', '1 tsp cayenne', 'Red oak wood'], instructions: ['Trim excess fat from tri-tip.', 'Mix Santa Maria style rub.', 'Season tri-tip all over.', 'Smoke at 250°F for 60-90 minutes.', 'Remove at 130°F for medium-rare.', 'Rest 10 minutes.', 'Slice thin against the grain.'] },
        { title: 'Smoked Beef Tenderloin', description: 'Elegant smoked beef tenderloin for special occasions.', prep_time: 20, cook_time: 60, servings: 8, ingredients: ['4 lb beef tenderloin', '2 tbsp olive oil', '2 tbsp black pepper', '1 tbsp kosher salt', '1 tbsp fresh rosemary', '4 cloves garlic'], instructions: ['Trim silver skin from tenderloin.', 'Tie with butcher twine for even shape.', 'Coat with oil and seasonings.', 'Smoke at 250°F for 45-60 minutes.', 'Remove at 125°F for medium-rare.', 'Rest 15 minutes before slicing.'] },
        { title: 'Smoked Prime Rib', description: 'Show-stopping smoked prime rib with herb crust.', prep_time: 30, cook_time: 240, servings: 10, ingredients: ['8 lb prime rib roast', '4 tbsp butter, softened', '4 cloves garlic, minced', '2 tbsp fresh rosemary', '2 tbsp fresh thyme', 'Salt and pepper'], instructions: ['Let roast come to room temp.', 'Mix butter with herbs and garlic.', 'Coat roast with herb butter.', 'Season with salt and pepper.', 'Smoke at 250°F for 3-4 hours.', 'Remove at 125°F internal.', 'Rest 30 minutes before carving.'] },
        { title: 'Smoked Beef Cheeks', description: 'Melt-in-your-mouth smoked beef cheeks.', prep_time: 15, cook_time: 360, servings: 4, ingredients: ['2 lb beef cheeks', '1 cup beef broth', '1/2 cup red wine', '1 onion, quartered', '4 cloves garlic', 'BBQ rub'], instructions: ['Season beef cheeks with rub.', 'Smoke at 250°F for approximately 3 hours.', 'Transfer to braising pan.', 'Add broth, wine, onion, garlic.', 'Cover and braise until internal temp reaches 205°F and meat is fork tender.', 'Serve with braising liquid.'] },
        { title: 'Smoked Beef Ribs Dino Style', description: 'Massive beef ribs with incredible smoke flavor.', prep_time: 15, cook_time: 420, servings: 4, ingredients: ['4 lb beef back ribs', '2 tbsp kosher salt', '2 tbsp black pepper', '1 tbsp garlic powder', 'Oak wood'], instructions: ['Remove membrane from ribs.', 'Season with salt, pepper, garlic.', 'Smoke at 275°F for approximately 6-7 hours.', 'Spritz occasionally.', 'Done when internal temp reaches 203°F and meat pulls from bone.', 'Rest 15 minutes before serving.'] },
        { title: 'Smoked Burgers', description: 'Juicy smoked burgers with amazing flavor.', prep_time: 15, cook_time: 60, servings: 6, ingredients: ['2 lb ground beef (80/20)', '1 tsp salt', '1 tsp pepper', '1 tsp garlic powder', '6 burger buns', 'Your favorite toppings'], instructions: ['Form beef into 6 patties.', 'Season both sides.', 'Smoke at 250°F for approximately 45 minutes.', 'Cook until internal temp reaches 160°F for well done or 145°F for medium.', 'Finish on hot grill for sear.', 'Add cheese if desired.', 'Serve on toasted buns.'] },
        { title: 'Smoked Meatloaf', description: 'Classic meatloaf with smoky BBQ glaze.', prep_time: 20, cook_time: 150, servings: 8, ingredients: ['2 lb ground beef', '1/2 cup breadcrumbs', '2 eggs', '1/2 cup onion, diced', '1/2 cup BBQ sauce', '2 tbsp Worcestershire'], instructions: ['Mix all ingredients except BBQ sauce.', 'Form into loaf shape.', 'Smoke at 250°F for 2 hours.', 'Brush with BBQ sauce.', 'Cook until 160°F internal.', 'Rest 10 minutes, slice and serve.'] },
        { title: 'Smoked Beef Bologna', description: 'Giant bologna smoked to perfection.', prep_time: 10, cook_time: 180, servings: 12, ingredients: ['5 lb beef bologna chub', '1/4 cup yellow mustard', '2 tbsp BBQ rub', '1 cup BBQ sauce'], instructions: ['Score bologna in crosshatch pattern.', 'Coat with mustard.', 'Apply BBQ rub.', 'Smoke at 275°F for approximately 3 hours.', 'Cook until internal temp reaches 160°F.', 'Glaze with BBQ sauce.', 'Slice thick and serve.'] },
        { title: 'Smoked Beef Clod', description: 'Traditional Texas beef shoulder clod.', prep_time: 20, cook_time: 600, servings: 20, ingredients: ['15 lb beef shoulder clod', '1/4 cup salt', '1/4 cup black pepper', '2 tbsp garlic powder', 'Oak wood'], instructions: ['Trim excess fat.', 'Season generously.', 'Smoke at 250°F for approximately 10 hours.', 'Wrap when bark is set.', 'Cook until internal temp reaches 203°F and is probe tender.', 'Rest 1 hour before slicing.'] },
        { title: 'Smoked Beef Jerky', description: 'Homemade smoked beef jerky.', prep_time: 30, cook_time: 240, servings: 8, ingredients: ['2 lb flank steak', '1/2 cup soy sauce', '1/4 cup Worcestershire', '2 tbsp brown sugar', '1 tsp garlic powder', '1 tsp onion powder', '1/2 tsp red pepper flakes'], instructions: ['Freeze beef slightly for easier slicing.', 'Slice 1/4 inch thick against grain.', 'Mix marinade ingredients.', 'Marinate beef overnight.', 'Pat dry and arrange on racks.', 'Smoke at 175°F for approximately 4 hours.', 'Jerky should reach 160°F internal temp and be dried but still pliable.', 'Store in airtight container.'] },
        { title: 'Smoked Oxtails', description: 'Rich, gelatinous smoked oxtails.', prep_time: 15, cook_time: 360, servings: 4, ingredients: ['4 lb oxtails', 'BBQ rub', '2 cups beef broth', '1 cup red wine', '2 onions, quartered', '4 cloves garlic'], instructions: ['Season oxtails with rub.', 'Smoke at 275°F for approximately 3 hours.', 'Transfer to Dutch oven.', 'Add broth, wine, onions, garlic.', 'Braise until internal temp reaches 205°F and meat is fall-off-the-bone tender.', 'Serve with braising liquid.'] },
        { title: 'Smoked Chuck Roast', description: 'Poor mans brisket - delicious smoked chuck.', prep_time: 15, cook_time: 360, servings: 8, ingredients: ['5 lb chuck roast', '2 tbsp salt', '2 tbsp pepper', '1 tbsp garlic powder', 'Beef broth for spritzing'], instructions: ['Season chuck roast all over.', 'Smoke at 250°F for 4 hours.', 'Wrap in butcher paper.', 'Cook until 203°F probe tender.', 'Rest 30 minutes.', 'Slice or pull and serve.'] },
        { title: 'Smoked Beef Ribs Korean Style', description: 'Korean BBQ inspired smoked beef short ribs.', prep_time: 25, cook_time: 300, servings: 6, ingredients: ['4 lb beef short ribs', '1/2 cup soy sauce', '1/4 cup sesame oil', '3 tbsp brown sugar', '4 cloves garlic', '1 Asian pear, grated', '2 tbsp gochujang'], instructions: ['Mix marinade ingredients.', 'Marinate ribs overnight.', 'Remove from marinade, pat dry.', 'Smoke at 275°F for approximately 5 hours.', 'Cook until internal temp reaches 203°F and probe tender.', 'Glaze with reserved marinade.', 'Garnish with sesame seeds.'] },
        { title: 'Smoked Picanha', description: 'Brazilian-style smoked top sirloin cap.', prep_time: 15, cook_time: 90, servings: 6, ingredients: ['3 lb picanha (sirloin cap)', '2 tbsp coarse salt', '1 tbsp black pepper', '1 tbsp garlic powder'], instructions: ['Score fat cap in crosshatch.', 'Season generously with salt.', 'Let rest 30 minutes.', 'Smoke at 250°F fat-side up.', 'Remove at 130°F internal.', 'Slice against grain and serve.'] },
        { title: 'Smoked Beef Back Ribs', description: 'Tender smoked beef back ribs with dry rub.', prep_time: 15, cook_time: 300, servings: 4, ingredients: ['2 racks beef back ribs', '2 tbsp salt', '2 tbsp pepper', '1 tbsp paprika', '1 tbsp garlic powder'], instructions: ['Remove membrane from ribs.', 'Mix rub ingredients.', 'Season ribs generously.', 'Smoke at 275°F for approximately 5 hours.', 'Done when internal temp reaches 203°F and meat pulls back from bone.', 'Rest 10 minutes before serving.'] },
        { title: 'Smoked Flank Steak', description: 'Quick-smoking flank steak with bold flavor.', prep_time: 10, cook_time: 45, servings: 4, ingredients: ['2 lb flank steak', '2 tbsp olive oil', '1 tbsp salt', '1 tbsp pepper', '1 tbsp garlic powder'], instructions: ['Coat steak with oil.', 'Season both sides.', 'Smoke at 225°F for 30-45 minutes.', 'Remove at 130°F internal.', 'Rest 10 minutes.', 'Slice thin against the grain.'] },
        { title: 'Smoked Beef Tongue', description: 'Tender smoked beef tongue tacos.', prep_time: 20, cook_time: 300, servings: 8, ingredients: ['3 lb beef tongue', 'BBQ rub', '1 onion', '4 cloves garlic', 'Bay leaves', 'Corn tortillas'], instructions: ['Season tongue with rub.', 'Smoke at 275°F for approximately 3 hours.', 'Braise with aromatics until internal temp reaches 200°F and meat is tender.', 'Cool slightly and peel skin.', 'Dice and serve in tortillas.', 'Top with onion and cilantro.'] },
        { title: 'Smoked Beef Shank', description: 'Fall-apart tender smoked and braised beef shank.', prep_time: 20, cook_time: 420, servings: 4, ingredients: ['4 beef shanks', 'BBQ rub', '2 cups beef broth', '1 cup red wine', '2 carrots', '2 celery stalks', '1 onion'], instructions: ['Season shanks with rub.', 'Smoke at 275°F for approximately 3 hours.', 'Transfer to braising dish.', 'Add vegetables and liquids.', 'Braise until internal temp reaches 205°F and meat is fall-apart tender.', 'Serve with vegetables and sauce.'] }
    ],
    lamb: [
        { title: 'Smoked Leg of Lamb', description: 'Mediterranean-inspired smoked leg of lamb with garlic and rosemary.', prep_time: 30, cook_time: 240, servings: 8, featured: 1, ingredients: ['7 lb bone-in leg of lamb', '8 cloves garlic', '1/4 cup fresh rosemary', '3 tbsp olive oil', '2 tbsp lemon zest', '1 tbsp salt', '1 tbsp black pepper', 'Apple wood'], instructions: ['Make slits all over lamb leg.', 'Insert garlic slivers into slits.', 'Mix rosemary, oil, lemon zest, salt, pepper.', 'Rub mixture all over lamb.', 'Refrigerate overnight.', 'Bring to room temp before smoking.', 'Smoke at 250°F for 4 hours.', 'Remove at 145°F for medium.', 'Rest 20 minutes before carving.'] },
        { title: 'Smoked Lamb Ribs', description: 'Tender lamb ribs with aromatic spice rub.', prep_time: 15, cook_time: 180, servings: 4, ingredients: ['2 racks lamb ribs', '2 tbsp cumin', '1 tbsp coriander', '1 tbsp paprika', '1 tsp cinnamon', '1 tbsp salt', '1 tbsp garlic powder'], instructions: ['Remove membrane from ribs.', 'Mix spices for rub.', 'Apply rub generously.', 'Smoke at 275°F for approximately 3 hours.', 'Wrap if needed for tenderness.', 'Ribs are done when internal temp reaches 195-203°F between the bones.', 'Rest before cutting.'] },
        { title: 'Smoked Lamb Shoulder', description: 'Pulled lamb shoulder with Middle Eastern spices.', prep_time: 25, cook_time: 420, servings: 10, featured: 1, ingredients: ['6 lb lamb shoulder, bone-in', '2 tbsp cumin', '2 tbsp coriander', '1 tbsp turmeric', '1 tbsp paprika', '1 tbsp salt', '6 cloves garlic'], instructions: ['Mix spices together.', 'Rub all over lamb shoulder.', 'Let marinate overnight.', 'Smoke at 250°F for approximately 6-7 hours.', 'Wrap at 165°F internal.', 'Pull when internal temp reaches 203°F and is probe tender.', 'Shred and serve with flatbread.'] },
        { title: 'Smoked Lamb Chops', description: 'Quick-smoked lamb chops with herb crust.', prep_time: 10, cook_time: 45, servings: 4, ingredients: ['8 lamb loin chops', '2 tbsp olive oil', '2 tbsp fresh mint, chopped', '1 tbsp fresh rosemary', '4 cloves garlic, minced', 'Salt and pepper'], instructions: ['Mix oil with herbs and garlic.', 'Coat chops with herb mixture.', 'Season with salt and pepper.', 'Smoke at 250°F for 30-45 minutes.', 'Remove at 145°F for medium.', 'Rest 5 minutes before serving.'] },
        { title: 'Smoked Lamb Kebabs', description: 'Ground lamb kebabs with Mediterranean flavors.', prep_time: 25, cook_time: 60, servings: 6, ingredients: ['2 lb ground lamb', '1 onion, grated', '4 cloves garlic, minced', '2 tbsp fresh parsley', '1 tbsp cumin', '1 tsp allspice', 'Salt and pepper'], instructions: ['Mix all ingredients well.', 'Form around skewers.', 'Refrigerate 1 hour.', 'Smoke at 275°F for approximately 45-60 minutes.', 'Cook until internal temp reaches 160°F.', 'Serve with tzatziki sauce.'] },
        { title: 'Moroccan Smoked Lamb Shanks', description: 'Aromatic lamb shanks with warm spices.', prep_time: 20, cook_time: 360, servings: 4, ingredients: ['4 lamb shanks', '2 tbsp ras el hanout', '1 can diced tomatoes', '1 cup chicken broth', '1 onion, sliced', 'Dried apricots', 'Chickpeas'], instructions: ['Season shanks with ras el hanout.', 'Smoke at 275°F for approximately 2 hours.', 'Transfer to braising pan.', 'Add tomatoes, broth, onion.', 'Braise until internal temp reaches 205°F and meat is fall-off-the-bone tender.', 'Add apricots and chickpeas.', 'Serve over couscous.'] },
        { title: 'Smoked Rack of Lamb', description: 'Elegant smoked rack of lamb with herb crust.', prep_time: 20, cook_time: 60, servings: 4, ingredients: ['2 racks of lamb, frenched', '2 tbsp Dijon mustard', '1 cup breadcrumbs', '2 tbsp fresh herbs', '2 tbsp butter, melted', 'Salt and pepper'], instructions: ['Season racks with salt and pepper.', 'Smoke at 250°F for 30 minutes.', 'Brush with Dijon mustard.', 'Mix breadcrumbs, herbs, butter.', 'Press crust onto lamb.', 'Continue smoking to 135°F.', 'Rest 10 minutes before slicing.'] },
        { title: 'Greek Smoked Lamb Leg', description: 'Greek-style lamb with lemon, oregano, and garlic.', prep_time: 30, cook_time: 300, servings: 10, ingredients: ['8 lb leg of lamb', '1/2 cup lemon juice', '1/4 cup olive oil', '8 cloves garlic', '3 tbsp dried oregano', 'Salt and pepper'], instructions: ['Make deep slits in lamb.', 'Insert garlic into slits.', 'Mix lemon, oil, oregano.', 'Pour over lamb, marinate overnight.', 'Smoke at 250°F for approximately 5 hours.', 'Remove when internal temp reaches 145°F for medium.', 'Rest 20 minutes before carving.'] },
        { title: 'Smoked Lamb Neck', description: 'Rich, gelatinous smoked lamb neck.', prep_time: 15, cook_time: 360, servings: 4, ingredients: ['3 lb lamb neck', 'BBQ rub', '2 cups lamb or beef broth', '1 cup red wine', 'Aromatics'], instructions: ['Season lamb neck with rub.', 'Smoke at 275°F for approximately 3 hours.', 'Transfer to braising pan.', 'Add broth and wine.', 'Braise until internal temp reaches 205°F and meat is fork tender.', 'Shred meat and serve.'] },
        { title: 'Smoked Lamb Breast', description: 'Budget-friendly smoked lamb breast.', prep_time: 15, cook_time: 300, servings: 6, ingredients: ['4 lb lamb breast', '2 tbsp cumin', '1 tbsp coriander', '1 tbsp garlic powder', '1 tbsp salt', '1 tsp black pepper'], instructions: ['Mix spices for rub.', 'Season lamb breast all over.', 'Smoke at 275°F for approximately 5 hours.', 'Cook until internal temp reaches 195-203°F and meat is tender.', 'Rest 15 minutes.', 'Slice between ribs and serve.'] },
        { title: 'Smoked Lamb Burgers', description: 'Juicy lamb burgers with feta and mint.', prep_time: 15, cook_time: 60, servings: 6, ingredients: ['2 lb ground lamb', '1/2 cup feta cheese', '2 tbsp fresh mint', '2 cloves garlic, minced', 'Salt and pepper', 'Pita bread'], instructions: ['Mix lamb with feta, mint, garlic.', 'Form into 6 patties.', 'Season with salt and pepper.', 'Smoke at 250°F for approximately 45 minutes.', 'Cook until internal temp reaches 160°F.', 'Sear quickly on hot grill.', 'Serve in pita with tzatziki.'] },
        { title: 'Smoked Lamb Meatballs', description: 'Mediterranean lamb meatballs with yogurt sauce.', prep_time: 25, cook_time: 60, servings: 6, ingredients: ['2 lb ground lamb', '1/2 cup breadcrumbs', '1 egg', '2 tbsp fresh parsley', '1 tbsp cumin', '4 cloves garlic'], instructions: ['Mix all meatball ingredients.', 'Form into golf ball-sized balls.', 'Smoke at 275°F for 45-60 minutes.', 'Internal temp should reach 160°F.', 'Serve with yogurt sauce.'] },
        { title: 'Smoked Stuffed Lamb Shoulder', description: 'Lamb shoulder stuffed with spinach and pine nuts.', prep_time: 35, cook_time: 300, servings: 8, ingredients: ['5 lb boneless lamb shoulder', '2 cups spinach', '1/2 cup pine nuts', '1/2 cup feta cheese', '4 cloves garlic', 'Fresh herbs'], instructions: ['Butterfly lamb shoulder.', 'Mix stuffing ingredients.', 'Spread stuffing over lamb.', 'Roll and tie with twine.', 'Season exterior.', 'Smoke at 275°F for approximately 5 hours.', 'Cook until internal temp reaches 195°F for pullable or 145°F for sliceable.', 'Rest before slicing.'] },
        { title: 'Turkish Smoked Lamb Kofte', description: 'Spiced lamb kofte on skewers.', prep_time: 20, cook_time: 45, servings: 6, ingredients: ['2 lb ground lamb', '1 onion, grated', '2 tbsp fresh parsley', '1 tbsp cumin', '1 tsp sumac', '1/2 tsp allspice', 'Salt'], instructions: ['Mix all ingredients thoroughly.', 'Form onto flat skewers.', 'Refrigerate 30 minutes.', 'Smoke at 300°F for approximately 30-45 minutes.', 'Cook until internal temp reaches 160°F.', 'Serve with flatbread and salad.'] },
        { title: 'Smoked Lamb Loin', description: 'Tender smoked lamb loin medallions.', prep_time: 15, cook_time: 60, servings: 4, ingredients: ['2 lb lamb loin', '2 tbsp olive oil', '1 tbsp herbes de Provence', '4 cloves garlic, minced', 'Salt and pepper'], instructions: ['Coat lamb with oil and garlic.', 'Season with herbs, salt, pepper.', 'Smoke at 250°F for 45-60 minutes.', 'Remove at 140°F internal.', 'Rest 10 minutes.', 'Slice into medallions.'] },
        { title: 'Smoked Lamb Tacos', description: 'Pulled lamb tacos with chimichurri.', prep_time: 20, cook_time: 360, servings: 8, ingredients: ['4 lb lamb shoulder', 'Taco seasoning', 'Corn tortillas', 'Fresh cilantro', 'Onion', 'Chimichurri sauce'], instructions: ['Season lamb with taco seasoning.', 'Smoke at 250°F for approximately 6 hours.', 'Pull when internal temp reaches 203°F and meat is tender.', 'Warm tortillas.', 'Top with lamb and chimichurri.', 'Garnish with onion and cilantro.'] },
        { title: 'Indian Spiced Smoked Lamb', description: 'Lamb with garam masala and yogurt marinade.', prep_time: 30, cook_time: 300, servings: 8, ingredients: ['5 lb leg of lamb', '1 cup yogurt', '2 tbsp garam masala', '1 tbsp turmeric', '1 tbsp ginger', '6 cloves garlic', 'Salt'], instructions: ['Mix yogurt with all spices.', 'Coat lamb with marinade.', 'Marinate overnight.', 'Smoke at 250°F for approximately 5 hours.', 'Cook until internal temp reaches 145°F for medium.', 'Rest 20 minutes.', 'Serve with naan and chutney.'] },
        { title: 'Smoked Lamb Osso Buco', description: 'Lamb shanks prepared osso buco style.', prep_time: 25, cook_time: 360, servings: 4, ingredients: ['4 lamb shanks', 'Salt and pepper', '1 cup white wine', '1 can crushed tomatoes', '2 carrots', '2 celery stalks', 'Gremolata'], instructions: ['Season and smoke shanks for approximately 2 hours.', 'Braise with wine and tomatoes.', 'Add vegetables.', 'Cook until internal temp reaches 205°F and meat is fork tender.', 'Prepare gremolata topping.', 'Serve over risotto.'] },
        { title: 'Smoked Lamb Saddle', description: 'Impressive whole lamb saddle roast.', prep_time: 30, cook_time: 180, servings: 8, ingredients: ['6 lb lamb saddle', '1/4 cup olive oil', '3 tbsp fresh rosemary', '3 tbsp fresh thyme', '8 cloves garlic', 'Salt and pepper'], instructions: ['Score fat on saddle.', 'Mix oil with herbs and garlic.', 'Rub all over lamb.', 'Smoke at 275°F for approximately 3 hours.', 'Cook until internal temp reaches 140°F for medium.', 'Rest 20 minutes.', 'Carve at the table.'] },
        { title: 'Smoked Lamb and Apricot Tagine', description: 'North African lamb tagine with dried fruit.', prep_time: 25, cook_time: 300, servings: 6, ingredients: ['3 lb lamb shoulder, cubed', '1 cup dried apricots', '1/2 cup almonds', '2 tbsp ras el hanout', '1 cinnamon stick', 'Honey', 'Chicken broth'], instructions: ['Season lamb with spices.', 'Smoke lamb cubes for approximately 2 hours.', 'Transfer to tagine or Dutch oven.', 'Add apricots, almonds, broth.', 'Simmer until internal temp reaches 195°F and meat is tender.', 'Drizzle with honey.', 'Serve over couscous.'] }
    ],
    chicken: [
        { title: 'Classic Smoked Whole Chicken', description: 'Perfectly smoked whole chicken with crispy skin and juicy meat.', prep_time: 20, cook_time: 180, servings: 6, featured: 1, ingredients: ['5 lb whole chicken', '2 tbsp olive oil', '2 tbsp paprika', '1 tbsp garlic powder', '1 tbsp onion powder', '1 tsp cayenne', '1 tbsp salt', '1 tbsp black pepper', 'Apple wood'], instructions: ['Remove giblets and pat chicken dry.', 'Coat with olive oil.', 'Mix all seasonings for rub.', 'Apply rub all over chicken, including under skin.', 'Let rest at room temp for 30 minutes.', 'Smoke at 275°F for 2.5-3 hours.', 'Chicken is done at 165°F in thickest part.', 'Rest 15 minutes before carving.'] },
        { title: 'Smoked Chicken Wings', description: 'Crispy smoked wings with your choice of sauce.', prep_time: 15, cook_time: 120, servings: 6, featured: 1, ingredients: ['4 lb chicken wings', '2 tbsp baking powder', '1 tbsp salt', '1 tbsp paprika', '1 tsp garlic powder', 'Your favorite wing sauce'], instructions: ['Pat wings completely dry.', 'Toss with baking powder and seasonings.', 'Refrigerate uncovered for 4 hours.', 'Smoke at 250°F for approximately 1.5 hours.', 'Increase to 375°F for 30 minutes for crispy skin.', 'Wings are done when internal temp reaches 175°F.', 'Toss in sauce and serve.'] },
        { title: 'Smoked Beer Can Chicken', description: 'Moist chicken cooked upright over a beer can.', prep_time: 15, cook_time: 150, servings: 4, ingredients: ['4 lb whole chicken', 'BBQ rub', '1 can beer', '2 tbsp butter'], instructions: ['Season chicken inside and out.', 'Open beer and drink half.', 'Add butter to can.', 'Lower chicken onto can.', 'Smoke at 275°F for approximately 2-2.5 hours.', 'Chicken is done when internal temp reaches 165°F in breast, 175°F in thigh.', 'Rest 10 minutes before carving.'] },
        { title: 'Smoked Chicken Thighs', description: 'Juicy bone-in thighs with crispy skin.', prep_time: 10, cook_time: 120, servings: 4, ingredients: ['8 bone-in chicken thighs', '2 tbsp olive oil', 'BBQ rub', 'BBQ sauce'], instructions: ['Pat thighs dry.', 'Coat with oil and rub.', 'Smoke at 275°F for 1.5 hours.', 'Sauce in last 15 minutes if desired.', 'Internal temp should reach 175°F.'] },
        { title: 'Smoked Chicken Quarters', description: 'Classic smoked leg quarters with crispy skin.', prep_time: 10, cook_time: 150, servings: 4, ingredients: ['4 chicken leg quarters', 'BBQ rub', 'Apple cider vinegar spray'], instructions: ['Season quarters with rub.', 'Smoke at 275°F for 2-2.5 hours.', 'Spritz hourly with vinegar.', 'Done at 175°F internal.', 'Rest 10 minutes before serving.'] },
        { title: 'Smoked Chicken Breast', description: 'Tender smoked chicken breast for meal prep.', prep_time: 15, cook_time: 90, servings: 4, ingredients: ['4 boneless chicken breasts', '2 tbsp olive oil', '1 tbsp salt', '1 tbsp pepper', '1 tbsp paprika'], instructions: ['Brine chicken for 2 hours.', 'Pat dry and coat with oil.', 'Season with spices.', 'Smoke at 250°F for 1-1.5 hours.', 'Remove at 160°F internal.', 'Rest 10 minutes before slicing.'] },
        { title: 'Smoked Spatchcock Chicken', description: 'Flattened chicken for even cooking and crispy skin.', prep_time: 20, cook_time: 120, servings: 4, ingredients: ['4 lb whole chicken', '4 tbsp butter, softened', '2 tbsp fresh herbs', '4 cloves garlic, minced', 'Salt and pepper'], instructions: ['Remove backbone with shears.', 'Press flat, breaking breastbone.', 'Mix butter with herbs and garlic.', 'Spread under and over skin.', 'Season with salt and pepper.', 'Smoke at 300°F for approximately 1.5-2 hours.', 'Chicken is done when breast reaches 165°F and thigh reaches 175°F.', 'Rest 10 minutes.'] },
        { title: 'Smoked Buffalo Chicken Dip', description: 'Creamy smoked chicken dip with buffalo kick.', prep_time: 20, cook_time: 60, servings: 12, ingredients: ['2 lb chicken breast', '8 oz cream cheese', '1/2 cup ranch dressing', '1/2 cup buffalo sauce', '1 cup shredded cheddar', 'Green onions'], instructions: ['Smoke chicken breast until internal temp reaches 165°F.', 'Shred chicken.', 'Mix all ingredients in cast iron.', 'Smoke at 275°F for approximately 45 minutes.', 'Stir and top with cheese.', 'Smoke until bubbly.', 'Serve with chips.'] },
        { title: 'Smoked Chicken Drumsticks', description: 'Kid-friendly smoked drumsticks.', prep_time: 10, cook_time: 120, servings: 6, ingredients: ['12 chicken drumsticks', 'BBQ rub', 'BBQ sauce'], instructions: ['Pat drumsticks dry.', 'Season with rub.', 'Smoke at 275°F for 1.5 hours.', 'Brush with sauce.', 'Cook 15 more minutes.', 'Done at 175°F internal.'] },
        { title: 'Smoked Chicken Salad', description: 'Classic chicken salad with smoked meat.', prep_time: 20, cook_time: 90, servings: 6, ingredients: ['2 lb chicken breast', '1/2 cup mayonnaise', '2 stalks celery, diced', '1/4 cup red onion, diced', '1 tbsp Dijon mustard', 'Salt and pepper'], instructions: ['Smoke chicken breast until internal temp reaches 165°F.', 'Cool and dice chicken.', 'Mix with mayo and vegetables.', 'Season to taste.', 'Refrigerate 1 hour.', 'Serve on bread or greens.'] },
        { title: 'Smoked Jerk Chicken', description: 'Caribbean-style jerk chicken with heat.', prep_time: 25, cook_time: 150, servings: 6, ingredients: ['8 chicken pieces', '1/4 cup jerk seasoning', '4 scotch bonnet peppers', '6 cloves garlic', '1/4 cup lime juice', '2 tbsp soy sauce', 'Fresh thyme'], instructions: ['Blend peppers, garlic, lime, soy, thyme.', 'Mix with jerk seasoning.', 'Marinate chicken overnight.', 'Smoke at 275°F for approximately 2-2.5 hours.', 'Chicken is done when internal temp reaches 165°F in breast, 175°F in thigh.', 'Serve with rice and peas.'] },
        { title: 'Smoked Lemon Herb Chicken', description: 'Bright, fresh smoked chicken with lemon.', prep_time: 15, cook_time: 180, servings: 6, ingredients: ['5 lb whole chicken', '2 lemons', '1/4 cup olive oil', '3 tbsp fresh herbs', '6 cloves garlic', 'Salt and pepper'], instructions: ['Zest and juice lemons.', 'Mix with oil, herbs, garlic.', 'Coat chicken inside and out.', 'Place lemon halves inside cavity.', 'Smoke at 275°F for approximately 3 hours.', 'Chicken is done when internal temp reaches 165°F in breast.', 'Rest before carving.'] },
        { title: 'Smoked Chicken Tacos', description: 'Pulled smoked chicken for tacos.', prep_time: 15, cook_time: 180, servings: 8, ingredients: ['3 lb chicken thighs', 'Taco seasoning', 'Corn tortillas', 'Salsa verde', 'Fresh cilantro', 'Onion'], instructions: ['Season thighs with taco spices.', 'Smoke at 275°F for approximately 2.5 hours.', 'Chicken is done when internal temp reaches 175°F.', 'Shred chicken.', 'Warm tortillas.', 'Assemble tacos with toppings.'] },
        { title: 'Smoked Teriyaki Chicken', description: 'Sweet teriyaki glazed smoked chicken.', prep_time: 20, cook_time: 150, servings: 6, ingredients: ['8 chicken thighs', '1 cup teriyaki sauce', '2 tbsp honey', '1 tbsp sesame oil', 'Sesame seeds', 'Green onions'], instructions: ['Marinate chicken in teriyaki.', 'Smoke at 275°F for approximately 2 hours.', 'Glaze with remaining sauce.', 'Continue until internal temp reaches 175°F.', 'Garnish with sesame and onions.'] },
        { title: 'Smoked Chicken Nachos', description: 'Loaded nachos with smoked chicken.', prep_time: 20, cook_time: 30, servings: 8, ingredients: ['2 cups smoked chicken, shredded', 'Tortilla chips', '2 cups shredded cheese', 'Jalapenos', 'Sour cream', 'Salsa', 'Guacamole'], instructions: ['Layer chips on sheet pan.', 'Top with chicken and cheese.', 'Smoke at 350°F until cheese melts.', 'Add toppings and serve.'] },
        { title: 'Alabama White Sauce Chicken', description: 'Smoked chicken with tangy Alabama white sauce.', prep_time: 15, cook_time: 180, servings: 6, ingredients: ['5 lb whole chicken', 'BBQ rub', '1 cup mayonnaise', '1/4 cup apple cider vinegar', '2 tbsp lemon juice', '1 tbsp horseradish', 'Salt and pepper'], instructions: ['Season chicken with rub.', 'Smoke at 275°F for approximately 3 hours.', 'Chicken is done when internal temp reaches 165°F in breast.', 'Mix white sauce ingredients.', 'Serve chicken with sauce.'] },
        { title: 'Smoked Chicken and Waffles', description: 'Brunch-worthy smoked fried chicken.', prep_time: 30, cook_time: 180, servings: 6, ingredients: ['8 chicken thighs', 'Buttermilk', 'Flour', 'Cajun seasoning', 'Waffles', 'Maple syrup'], instructions: ['Soak chicken in buttermilk overnight.', 'Smoke at 250°F for approximately 2 hours until internal temp reaches 175°F.', 'Dredge in seasoned flour.', 'Fry until golden and crispy.', 'Serve over waffles with syrup.'] },
        { title: 'Smoked Chicken Quesadillas', description: 'Cheesy quesadillas with smoked chicken.', prep_time: 15, cook_time: 15, servings: 4, ingredients: ['2 cups smoked chicken', 'Flour tortillas', '2 cups Mexican cheese', 'Peppers and onions', 'Sour cream', 'Salsa'], instructions: ['Saute peppers and onions.', 'Layer tortilla with cheese and chicken.', 'Add vegetables, fold in half.', 'Grill until crispy.', 'Serve with sour cream and salsa.'] },
        { title: 'Smoked Chicken Caesar Salad', description: 'Classic Caesar with smoked chicken.', prep_time: 15, cook_time: 90, servings: 4, ingredients: ['2 chicken breasts', 'Romaine lettuce', 'Caesar dressing', 'Parmesan cheese', 'Croutons', 'Lemon'], instructions: ['Smoke chicken breasts at 250°F for approximately 1-1.5 hours.', 'Remove when internal temp reaches 165°F.', 'Cool and slice.', 'Chop romaine lettuce.', 'Toss with dressing.', 'Top with chicken, cheese, croutons.'] },
        { title: 'Thai Smoked Chicken', description: 'Coconut curry marinated smoked chicken.', prep_time: 25, cook_time: 150, servings: 6, ingredients: ['8 chicken pieces', '1 can coconut milk', '3 tbsp red curry paste', '2 tbsp fish sauce', '2 tbsp brown sugar', 'Fresh basil'], instructions: ['Mix coconut milk with curry paste.', 'Add fish sauce and sugar.', 'Marinate chicken 4 hours.', 'Smoke at 275°F for approximately 2.5 hours.', 'Chicken is done when internal temp reaches 165°F in breast, 175°F in thigh.', 'Garnish with fresh basil.'] }
    ],
    seafood: [
        { title: 'Cedar Plank Smoked Salmon', description: 'Classic Pacific Northwest smoked salmon on cedar.', prep_time: 20, cook_time: 60, servings: 6, featured: 1, ingredients: ['2 lb salmon fillet', '1/4 cup brown sugar', '2 tbsp salt', '1 tbsp black pepper', '1 tbsp dill', 'Cedar plank', 'Alder wood'], instructions: ['Soak cedar plank for 2 hours.', 'Mix brown sugar, salt, pepper, dill.', 'Apply cure to salmon flesh.', 'Refrigerate 4 hours.', 'Rinse and pat dry.', 'Place salmon on plank.', 'Smoke at 225°F for 45-60 minutes.', 'Salmon is done at 145°F.'] },
        { title: 'Smoked Shrimp', description: 'Quick-smoked shrimp with Cajun spices.', prep_time: 15, cook_time: 30, servings: 4, featured: 1, ingredients: ['2 lb large shrimp, peeled', '4 tbsp butter, melted', '2 tbsp Cajun seasoning', '4 cloves garlic, minced', 'Lemon wedges', 'Fresh parsley'], instructions: ['Toss shrimp with butter, seasoning, garlic.', 'Arrange on smoker rack or in pan.', 'Smoke at 225°F for 20-30 minutes.', 'Shrimp are done when pink and opaque.', 'Squeeze lemon over top.', 'Garnish with parsley.'] },
        { title: 'Smoked Lobster Tails', description: 'Decadent smoked lobster with garlic butter.', prep_time: 15, cook_time: 45, servings: 4, ingredients: ['4 lobster tails', '1/2 cup butter', '4 cloves garlic', '1 tbsp lemon juice', 'Fresh parsley', 'Salt'], instructions: ['Split lobster tails lengthwise.', 'Melt butter with garlic.', 'Brush lobster with garlic butter.', 'Smoke at 225°F for 30-45 minutes.', 'Baste every 10 minutes.', 'Serve with remaining butter.'] },
        { title: 'Smoked Trout', description: 'Whole smoked trout with herbs.', prep_time: 20, cook_time: 90, servings: 4, ingredients: ['4 whole trout, cleaned', '1/4 cup salt', '2 tbsp brown sugar', 'Fresh dill', 'Lemon slices', 'Alder wood'], instructions: ['Brine trout for 2 hours.', 'Rinse and pat dry.', 'Stuff cavity with dill and lemon.', 'Smoke at 200°F for 1.5 hours.', 'Fish should flake easily.'] },
        { title: 'Smoked Oysters', description: 'Smoky oysters on the half shell.', prep_time: 15, cook_time: 15, servings: 4, ingredients: ['24 fresh oysters', '1/2 cup butter', '4 cloves garlic, minced', 'Hot sauce', 'Parmesan cheese', 'Fresh parsley'], instructions: ['Shuck oysters carefully.', 'Mix butter with garlic.', 'Top each oyster with butter.', 'Smoke at 300°F for 10-15 minutes.', 'Add cheese in last 5 minutes.', 'Finish with hot sauce.'] },
        { title: 'Smoked Crab Legs', description: 'King crab legs with smoky flavor.', prep_time: 10, cook_time: 30, servings: 4, ingredients: ['4 lb king crab legs', '1 cup butter', '4 cloves garlic', '1 tbsp Old Bay', 'Lemon wedges'], instructions: ['Split crab legs partially.', 'Smoke at 250°F for 25-30 minutes.', 'Melt butter with garlic and Old Bay.', 'Serve crab with seasoned butter.'] },
        { title: 'Smoked Mahi Mahi', description: 'Tropical smoked mahi mahi with mango salsa.', prep_time: 20, cook_time: 45, servings: 4, ingredients: ['4 mahi mahi fillets', '2 tbsp olive oil', '1 tbsp jerk seasoning', 'Mango salsa', 'Lime wedges'], instructions: ['Coat fish with oil.', 'Season with jerk spices.', 'Smoke at 225°F for 35-45 minutes.', 'Fish is done at 145°F.', 'Top with mango salsa.'] },
        { title: 'Smoked Scallops', description: 'Bacon-wrapped smoked scallops.', prep_time: 20, cook_time: 45, servings: 4, ingredients: ['1 lb large sea scallops', '8 strips bacon', '2 tbsp butter', '1 tbsp lemon juice', 'Fresh chives'], instructions: ['Wrap each scallop with bacon.', 'Secure with toothpick.', 'Smoke at 275°F for 30-45 minutes.', 'Bacon should be crispy.', 'Drizzle with lemon butter.'] },
        { title: 'Smoked Tuna Steaks', description: 'Seared smoked ahi tuna.', prep_time: 15, cook_time: 30, servings: 4, ingredients: ['4 ahi tuna steaks', '2 tbsp sesame oil', '2 tbsp soy sauce', 'Sesame seeds', 'Wasabi', 'Pickled ginger'], instructions: ['Marinate tuna in soy and sesame oil.', 'Coat with sesame seeds.', 'Cold smoke at 150°F for 20 minutes.', 'Sear quickly on hot grill.', 'Serve rare with wasabi.'] },
        { title: 'Smoked Catfish', description: 'Southern-style smoked catfish.', prep_time: 15, cook_time: 90, servings: 4, ingredients: ['4 catfish fillets', '2 tbsp Cajun seasoning', '2 tbsp butter, melted', 'Lemon wedges', 'Tartar sauce'], instructions: ['Pat catfish dry.', 'Brush with butter.', 'Season with Cajun spices.', 'Smoke at 225°F for 1-1.5 hours.', 'Serve with tartar sauce.'] },
        { title: 'Smoked Swordfish', description: 'Meaty swordfish steaks with herb butter.', prep_time: 15, cook_time: 45, servings: 4, ingredients: ['4 swordfish steaks', '2 tbsp olive oil', '1 tbsp herbs de Provence', 'Herb compound butter', 'Lemon'], instructions: ['Brush fish with oil.', 'Season with herbs.', 'Smoke at 225°F for 35-45 minutes.', 'Top with herb butter to serve.'] },
        { title: 'Smoked Clams', description: 'Smoky littleneck clams.', prep_time: 10, cook_time: 20, servings: 4, ingredients: ['4 lb littleneck clams', '1/2 cup white wine', '4 tbsp butter', '4 cloves garlic', 'Fresh parsley', 'Crusty bread'], instructions: ['Scrub clams clean.', 'Place in smoker-safe pan.', 'Add wine, butter, garlic.', 'Smoke at 300°F until clams open.', 'Discard any that dont open.', 'Serve with bread for dipping.'] },
        { title: 'Smoked Mackerel', description: 'Rich, oily smoked mackerel.', prep_time: 30, cook_time: 120, servings: 4, ingredients: ['4 whole mackerel', '1/4 cup salt', '2 tbsp sugar', 'Bay leaves', 'Peppercorns'], instructions: ['Brine mackerel for 1 hour.', 'Rinse and dry thoroughly.', 'Air dry 1 hour until tacky.', 'Smoke at 200°F for 2 hours.', 'Serve with crackers and cream cheese.'] },
        { title: 'Smoked Shrimp Boil', description: 'Complete shrimp boil on the smoker.', prep_time: 20, cook_time: 60, servings: 6, ingredients: ['2 lb shrimp', '1 lb smoked sausage', '2 lb baby potatoes', '4 ears corn', 'Old Bay seasoning', '1/2 cup butter'], instructions: ['Layer potatoes in foil packet.', 'Smoke at 275°F for 30 minutes.', 'Add sausage and corn.', 'Cook 20 more minutes.', 'Add shrimp for final 10 minutes.', 'Toss with butter and Old Bay.'] },
        { title: 'Smoked Halibut', description: 'Delicate smoked halibut with caper sauce.', prep_time: 15, cook_time: 45, servings: 4, ingredients: ['4 halibut fillets', '2 tbsp olive oil', 'Salt and white pepper', '1/4 cup capers', 'Lemon butter sauce'], instructions: ['Brush halibut with oil.', 'Season with salt and pepper.', 'Smoke at 225°F for 35-45 minutes.', 'Make lemon butter sauce with capers.', 'Drizzle over fish to serve.'] },
        { title: 'Smoked Tilapia', description: 'Mild smoked tilapia with citrus.', prep_time: 15, cook_time: 45, servings: 4, ingredients: ['4 tilapia fillets', '2 tbsp olive oil', '1 tbsp paprika', '1 tsp garlic powder', 'Orange slices', 'Fresh cilantro'], instructions: ['Brush fish with oil.', 'Season with spices.', 'Top with orange slices.', 'Smoke at 225°F for 35-45 minutes.', 'Garnish with cilantro.'] },
        { title: 'Smoked Mussels', description: 'Smoky mussels in white wine.', prep_time: 15, cook_time: 20, servings: 4, ingredients: ['3 lb mussels', '1 cup white wine', '4 tbsp butter', '4 cloves garlic', 'Shallots', 'Fresh parsley'], instructions: ['Clean and debeard mussels.', 'Place in cast iron pan.', 'Add wine, butter, garlic, shallots.', 'Smoke at 350°F until mussels open.', 'Garnish with parsley.', 'Serve with crusty bread.'] },
        { title: 'Smoked Sea Bass', description: 'Elegant smoked Chilean sea bass.', prep_time: 15, cook_time: 60, servings: 4, ingredients: ['4 sea bass fillets', '2 tbsp miso paste', '1 tbsp mirin', '1 tbsp sake', 'Sesame oil'], instructions: ['Mix miso glaze ingredients.', 'Coat fish with glaze.', 'Marinate 2 hours.', 'Smoke at 225°F for 45-60 minutes.', 'Glaze again halfway through.'] },
        { title: 'Smoked Cod', description: 'Traditional smoked cod for fish cakes.', prep_time: 30, cook_time: 120, servings: 6, ingredients: ['2 lb cod fillets', '1/4 cup salt', '2 tbsp sugar', 'Cold water', 'Alder wood'], instructions: ['Brine cod for 30 minutes.', 'Rinse and pat dry.', 'Air dry until tacky pellicle forms.', 'Smoke at 200°F for 2 hours.', 'Flake for fish cakes or serve as is.'] },
        { title: 'Smoked Salmon Dip', description: 'Creamy smoked salmon spread.', prep_time: 15, cook_time: 0, servings: 8, ingredients: ['1 lb smoked salmon', '8 oz cream cheese', '1/4 cup sour cream', '2 tbsp fresh dill', '1 tbsp lemon juice', 'Capers'], instructions: ['Flake smoked salmon.', 'Beat cream cheese until smooth.', 'Mix in sour cream and lemon.', 'Fold in salmon and dill.', 'Top with capers.', 'Serve with crackers.'] }
    ]
};

// Generate slug from title
function generateSlug(title) {
    return title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .substring(0, 100);
}

// Seed the database
async function seed() {
    console.log('Waiting for database initialization...');
    await db.initPromise;

    console.log('Starting database seed...');

    // Clear existing recipes
    db.execute('DELETE FROM recipes');
    console.log('Cleared existing recipes.');

    // Get category IDs
    const categories = db.queryAll('SELECT id, slug FROM categories');
    const categoryMap = {};
    categories.forEach(cat => {
        categoryMap[cat.slug] = cat.id;
    });

    let totalInserted = 0;

    // Insert recipes for each category
    Object.entries(recipes).forEach(([category, categoryRecipes]) => {
        const categoryId = categoryMap[category];
        console.log(`Inserting ${category} recipes...`);

        categoryRecipes.forEach(recipe => {
            const slug = generateSlug(recipe.title);

            db.execute(`
                INSERT INTO recipes (
                    title, slug, description, extended_description, ingredients, instructions,
                    prep_time, cook_time, servings, category_id, image_url, featured
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            `, [
                recipe.title,
                slug,
                recipe.description,
                recipe.extended_description || null,
                JSON.stringify(recipe.ingredients),
                JSON.stringify(recipe.instructions),
                recipe.prep_time,
                recipe.cook_time,
                recipe.servings,
                categoryId,
                recipe.image_url || null,
                recipe.featured || 0
            ]);
            totalInserted++;
        });
    });

    console.log(`\nSeeding complete! Inserted ${totalInserted} recipes.`);

    // Show summary
    const summary = db.queryAll(`
        SELECT c.name, COUNT(r.id) as count
        FROM categories c
        LEFT JOIN recipes r ON c.id = r.category_id
        GROUP BY c.id
    `);

    console.log('\nRecipes by category:');
    summary.forEach(row => {
        console.log(`  ${row.name}: ${row.count}`);
    });

    process.exit(0);
}

// Run seed
seed().catch(err => {
    console.error('Seed error:', err);
    process.exit(1);
});
